<?php
return [
    'MASTER_CODES' => [
        'USE_FLAG' => 1,
        'DEPT_TYPE' => 6,
        'USER_LVL' => 7,
        'REQ_AREA1_DIV' => 8,
        'STATION_TYPE' => 9,
        'EQUIP_KIND' => 10,
        'TOUCH_MTH' => 11,
        'PURC_MTH' => 12,
        'OS_KIND' => 13,
        'LOCKER_KIND' => 16,
        'MCU_KIND' => 17,
        'CTRL_BOX_TYPE' => 18,
        'SUB_MCU_YN' => 19,
        'COMPTR_TYPE' => 20,
        'MONTR_SIZE' => 22,
        'LOCK_KIND' => 23,
        'ASK_TYPE' => 24,
        'DEFECT_TYPE' => 25,
        'PROG_STATUS' => 26,
        'EMERGENCY_TYPE' => 27,
        'MAINT_TYPE' => 28,
    ],
    'DETAIL_CODES' => [
        'USE_FLAG' => [
            'YES' => 1,
            'NO' => 2
        ],
        'DEPT_TYPE' => [
            'DIVISION' => 8,
            'DEPARTMENT' => 9,
            'TEAM' => 10,
        ],
        'USER_LVL' => [
            'ADMIN' => 11,
            'STAFF' => 12,
            'CALL_CENTER_STAFF' => 13,
            'APARTMENT_MANAGER' => 14,
            'GUEST' => 15,
        ],
        'EQUIP_KIND' => [
            'COMPUTER' => 24,
            'MONITOR' => 25,
            'WEBCAM' => 26,
            'PRINTER' => 27,
            'RFID_READER' => 28,
            'CASH_TERMINAL' => 29,
            'CARD_TERMINAL' => 30,
            'BANKNOTE_INSERTER' => 31,
            'BANKNOTE_DISPENSER' => 32,
            'COIN_INSERTER' => 33,
            'COIN_DISPENSER' => 34,
        ],
        'PROG_STATUS' => [
            'RECEIPT' => 84,
            'COMPLETE_RECEIPT' => 85,
            'COMPLETE' => 86,
        ],
    ],

    'NON_MEMBER_AS_RECEPTION' => '비회원 A/S 접수',

    'MENU' => [
        'EDIT_AS' => 1,
        'DETAIL_AS' => 2,
        'HANDLE_AS' => 3,
        'STATIONS' => 4,
        'STATION_LOCKERS' => 5,
        'STATIONS_DETAIL' => 6,
        'LOCKERS' => 7,
        'LOCKERS_STATION' => 8,
        'LOCKERS_DETAIL' => 9,
        'LOCKER_FREE' => 10,
        'REGISTER_USER' => 11,
        'APPROVAL_USERS' => 12,
        'USERS' => 13,
        'EQUIPMENTS' => 14,
        'CREATE_NOTICE' => 15,
        'LIST_NOTICES' => 16,
        'DETAIL_NOTICES' => 17,
        'DEPARTMENTS' => 18,
        'CODES' => 19,
        'PERMISSIONS' => 20,
    ]
];
